name: Node CI

on: [push]

jobs:  
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Build use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: mkdir casanet-bin && mkdir .pkg-cache && cd .pkg-cache && export PKG_CACHE_PATH=$(pwd) && echo $PKG_CACHE_PATH && mkdir v2.6 && cd v2.6 && curl -L https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.2.0-linux-armv7 --output fetched-v12.18.1-linux-armv7 && chmod 777 fetched-v12.18.1-linux-armv7 && cd ../../ && cd frontend && npm ci && cd ../ && cd backend && npm ci && npm run bundle && cp -v bundle/* ../casanet-bin
      env:
        CI: true
      path: casanet-bin
     