name: Node CI

on: [push]

jobs:  
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Build use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: mkdir .pkg-cache && cd .pkg-cache && mkdir v2.6
    - run: curl -L https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.2.0-linux-armv7 --output .pkg-cache/v2.6/fetched-v12.18.1-linux-armv7
    - run: cd .pkg-cache/v2.6 && chmod 777 fetched-v12.18.1-linux-armv7
    - run: cd frontend && npm ci
    - run: echo $PKG_CACHE_PATH && cd backend && npm ci && npm run bundle
      env:
        PKG_CACHE_PATH: ~/.pkg-cache
        CI: true
     